name: Go tests
on:
  push:
  pull_request:
  schedule: # daily at 09:42 UTC
    - cron: '42 9 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { go-version: stable, deps: locked }
          - { go-version: oldstable, deps: locked }
          - { go-version-file: go.mod, deps: locked }
          - { go-version: stable, deps: latest }
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: ${{ matrix.go-version-file }}
      - uses: geomys/sandboxed-step@v1.2.0
        with:
          run: |
            sudo apt-get update && sudo apt-get install -y psmisc # for killall
            curl --fail --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl_4.1.0_amd64.deb
            sudo apt-get install -y ./hurl_4.1.0_amd64.deb
            if [ "${{ matrix.deps }}" = "latest" ]; then
              go get -u -t ./...
            fi
            go test ./...
            go test -short -race ./...
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: geomys/sandboxed-step@v1.1.1
        with:
          run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: geomys/sandboxed-step@v1.1.1
        with:
          run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
